[application]

# App (Project) Name
name = "magenroy-website"
out_dir = "docs"
default_platform = "web"

[bundle]
# icon = []
category = "Personal Website"
short_description = "Personal website of Roy Magen"
long_description = "Personal website of Roy Magen"

[web.app]
# base_path = "public"

# HTML title tag content
title = "Roy Magen"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
